plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':model')
    implementation 'org.apache.thrift:libthrift:0.19.0'
    implementation 'org.slf4j:slf4j-simple:2.0.16'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

def thriftSrcDir = "$projectDir/src/main/thrift"
def thriftGenDir = "$buildDir/generated-sources/thrift"

tasks.register('generateThrift') {
    inputs.dir(thriftSrcDir)
    outputs.dir(thriftGenDir)
    doLast {
        mkdir(thriftGenDir)
        exec {
            commandLine 'thrift', '--gen', 'java:generated_annotations=suppress',
                    '-out', thriftGenDir, "$thriftSrcDir/movie.thrift"
        }
    }
}

sourceSets {
    main {
        java {
            srcDir thriftGenDir
        }
    }
}

compileJava.dependsOn generateThrift

test {
    useJUnitPlatform()
}
